### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Firstyear** [Firstyear/kanidm#21]
Support a docker deployment, with proper documentation and examples of how to perform tasks (like backups!).

**Comment by phozzy** [comment]
Do you have a crate for your application?

**Comment by Firstyear** [comment]
Hey @phozzy: I haven't published any of the libraries to crates.io yet, because they have been undergoing so much change that I didn't feel they were releasable for people to link/use them. What did you want to try out with them? I can probably write something up to help you achieve and test it :)

**Comment by phozzy** [comment]
I just saw your current dockerfile, and I thought that it can be improved if there is a crate ready.

**Comment by Firstyear** [comment]
Ahhh yep of course.

There is an argument to keeping it as a source build, because then we could have it hooked in with dockerhub and on git commit rebuild the images rather than relying on crates though?

**Comment by Firstyear** [comment]
This was added as part of #123, so now it needs documentation as part of #128
