### ISSUE TITLE
Seperate read and write actors

### ISSUE THREAD

**Issue by Firstyear** [Firstyear/kanidm#54]
At the moment, the query server uses actors as a simple thread pool, but it should be split so that there is a single write actor, multiple read actors, and split idm actors.

**Comment by NiryaAestus** [comment]
Sounds like CQRS which is a nice design pattern.

**Comment by Firstyear** [comment]
Didn't know that! Good to learn about it. The reality is actually that we use MVCC structures (currently a COWCell type, but someone is working on a concurrent tree for rust that'll we'll change to). So by having the threads seperated, because we take the locks early in the mvcc write txn acquisition, there isn't much point in having multiple writers - they wouldn't be able to do meaningful work and advance, when we could be yielding and letting a search or authentication event progress. 

In addition by having it as one thread, we also reduce cache-line contention on the MVCC structure locks on the write half of the structure, and it keeps the cpu cache of that thread hot for the write ops and such. 

Currently it's all on one pool because I'm lazy, and I need to spend some time to split up and fix up some stuff in the server start up in core.rs - you'll probably see that there is a pattern of "ohh look william has been the only one doing this for a year, so there are somethings that I said I'd do later". So any cleanups or ideas or ways to improve my code would be wonderful too in general.
