### ISSUE TITLE
Determine an approach to username change (add default self-write acp)

### ISSUE THREAD

**Issue by JJJollyjim** [Firstyear/kanidm#90]
It's not super clear whether this is already covered by the name change docs in ethics/EXAMPLES.md

Username change is tricky, but it can be somewhat necessary for the same reasons as a displayName change.

I expect it would be very difficult to support username change with certain external integrations, but it would be nice to have a best-effort approach to it (and support that by not using the username as a sole id/key when possible)

**Comment by Firstyear** [comment]
I think this is already (mostly) solved - I've considered that the "name" attribute aka username should be changeable from day one.

Internally, all links between members/memberof and others are by uuid. We use a uuid2name and name2uuid function between the protocol types to the internal types, and in reverse on presentation. IE when you modify your membership to a group you say "present(member, william)" we actually translate this to present(member, <uuid>). When you change the name, you're really only changing the name on the entry. 

Even with name, we enforce only uniqueness in the live entries (recycle/tombstones are ignored). So provided it doesn't have a conflict, we'll allow the change. 

Today, it looks like I have forgotten (opps!) to add the self-write access control - so I'll fix this up shortly :) 

By default every person should have self write on name, displayname, legalname and a few others.
